### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by aryan1107** [Writer-Sonic/Ai-Image#1]
Please Create New Issue for any support

**Comment by designpeople** [comment]
Hi aryan I tried your image generator was great until it got stuck on it being busy would not come out of that uninstalled reinstalled same problem I had purchased a subscription but have cancelled as a result which is pity because the program is really cool .
Would like to carry on using it but as mentioned unable too.

**Comment by aryan1107** [comment]
Hi there yes I am aware of this problem sorry for the situation, there's sudden increase in users and I am trying to increase the capacity.

**Comment by designpeople** [comment]
Ok thanks for the update do you know when you will resolve this ? 
Also great you are experiencing a growth of users 👍

**Comment by aryan1107** [comment]
Hi there, I have sent update now it's being reviewed by Apple and it will be approved by them soon. Since GPU costs a lot and I want users to keep generating without any limit. I can only increase capacity to certain limit as I have limited funds. In future if it doesn't work due to sudden increase. Users might just have to wait. Or another option is I would have to charge for image generation which I dont want.

Please wait for another app update soon it should work.
